name: Discord Alert on Push or Merge

on:
  push:
    branches:
      - master

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🚀 Novo push ou merge no branch **main**!\nCommit por: ${{ github.actor }}\nMensagem: ${{ github.event.head_commit.message }}"
