name: Testes Unitários

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código
      - name: Check out code
        uses: actions/checkout@v3

      # Configura o Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      # Instala dependências
      - name: Instalar dependências
        run: python -m pip install --upgrade pip

      # Rodar os testes unitários
      - name: Rodar os testes unitários
        run: python teste_unitario.py  # Executa o seu script de testes
