name: Testes Unitários

on:
  push:
    branches:
      - master  # Ou a branch que você está usando (ex: main)
  pull_request:
    branches:
      - master  # Ou a branch que você está usando

jobs:
  test:
    runs-on: ubuntu-latest  # Roda em uma máquina virtual com Ubuntu

    steps:
      # Faz checkout do código
      - name: Check out code
        uses: actions/checkout@v3

      # Configura o Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Ou qualquer versão do Python que você esteja usando

      # Instala dependências
      - name: Instalar dependências
        run: python -m pip install --upgrade pip

      # Rodar os testes unitários
      - name: Rodar os testes unitários
        run: python tests/teste_unitario.py  # Caminho correto para o arquivo de testes
